// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Thing struct {
	ID             int64
	Structure      sql.NullString
	Type           sql.NullString
	Category       sql.NullString
	Classification sql.NullString
	Title          sql.NullString
	Path           sql.NullString
}
