// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: things.sql

package database

import (
	"context"
)

const getThingById = `-- name: GetThingById :one
SELECT id, structure, type, category, classification, title, path FROM things
WHERE id = ? LIMIT 1
`

func (q *Queries) GetThingById(ctx context.Context, id int64) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThingById, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.Structure,
		&i.Type,
		&i.Category,
		&i.Classification,
		&i.Title,
		&i.Path,
	)
	return i, err
}
